import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "@/app/source/animation.css";
import "@/app/source/media.css";
import "@/app/source/loader.css";
import "@/app/source/scroll.css";
import ClientSideRender from "@/app/client-side-render";
import ClientSideRenderGlobal from "@/app/client-side-render-global";

export const metadata = {
  title: "Okki Shop",
  description: "Generated by create next app",
  other: {
    'mobile-web-app-capable': 'yes',
    'apple-mobile-web-app-capable': 'yes',
  },
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        {/* <Bootstrap /> */}
        <body>
          <ClientSideRenderGlobal />
          <div className="container" style={{ maxWidth: '1100px', width: '100%' }}>
            <ClientSideRender />
            {children}
          </div>
        </body>
      </html>
  );
}
